/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEWS;

/**
 *
 * @author devmat
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelTelaPrincipal = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        areaDeCalculo = new javax.swing.JTextField();
        divisao = new javax.swing.JButton();
        adicao = new javax.swing.JButton();
        n3 = new javax.swing.JButton();
        n4 = new javax.swing.JButton();
        n5 = new javax.swing.JButton();
        subtracao = new javax.swing.JButton();
        n9 = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        parenteses = new javax.swing.JButton();
        apagar = new javax.swing.JButton();
        multiplicacao = new javax.swing.JButton();
        n8 = new javax.swing.JButton();
        n1 = new javax.swing.JButton();
        n2 = new javax.swing.JButton();
        n0 = new javax.swing.JButton();
        n6 = new javax.swing.JButton();
        n7 = new javax.swing.JButton();
        virgula = new javax.swing.JButton();
        limparTudo = new javax.swing.JButton();
        porcentagem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));
        setResizable(false);

        PainelTelaPrincipal.setBackground(new java.awt.Color(204, 204, 255));

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("CALCULADORA");

        areaDeCalculo.setEditable(false);
        areaDeCalculo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        areaDeCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaDeCalculoActionPerformed(evt);
            }
        });

        divisao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        divisao.setText("/");
        divisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisaoActionPerformed(evt);
            }
        });

        adicao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        adicao.setText("+");
        adicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicaoActionPerformed(evt);
            }
        });

        n3.setText("3");
        n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n3ActionPerformed(evt);
            }
        });

        n4.setText("4");
        n4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n4ActionPerformed(evt);
            }
        });

        n5.setText("5");
        n5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n5ActionPerformed(evt);
            }
        });

        subtracao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subtracao.setText("-");
        subtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtracaoActionPerformed(evt);
            }
        });

        n9.setText("9");
        n9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n9ActionPerformed(evt);
            }
        });

        igual.setText("=");
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });

        parenteses.setText("( )");
        parenteses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentesesActionPerformed(evt);
            }
        });

        apagar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Devmat\\Documents\\NetBeansProjects\\CALCULADORA\\src\\main\\java\\IMG\\cancelar.png")); // NOI18N
        apagar.setText("x");
        apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarActionPerformed(evt);
            }
        });

        multiplicacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        multiplicacao.setText("x");
        multiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicacaoActionPerformed(evt);
            }
        });

        n8.setText("8");
        n8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n8ActionPerformed(evt);
            }
        });

        n1.setText("1");
        n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1ActionPerformed(evt);
            }
        });

        n2.setText("2");
        n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n2ActionPerformed(evt);
            }
        });

        n0.setText("0");
        n0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n0ActionPerformed(evt);
            }
        });

        n6.setText("6");
        n6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n6ActionPerformed(evt);
            }
        });

        n7.setText("7");
        n7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n7ActionPerformed(evt);
            }
        });

        virgula.setText(",");
        virgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                virgulaActionPerformed(evt);
            }
        });

        limparTudo.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        limparTudo.setText("AC");
        limparTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparTudoActionPerformed(evt);
            }
        });

        porcentagem.setText("%");
        porcentagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porcentagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelTelaPrincipalLayout = new javax.swing.GroupLayout(PainelTelaPrincipal);
        PainelTelaPrincipal.setLayout(PainelTelaPrincipalLayout);
        PainelTelaPrincipalLayout.setHorizontalGroup(
            PainelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTelaPrincipalLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(PainelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelTelaPrincipalLayout.createSequentialGroup()
                        .addGroup(PainelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PainelTelaPrincipalLayout.createSequentialGroup()
                                .addComponent(titulo)
                                .addGap(16, 16, 16))
                            .addGroup(PainelTelaPrincipalLayout.createSequentialGroup()
                                .addGroup(PainelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelTelaPrincipalLayout.createSequentialGroup()
                                        .addGroup(PainelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(n3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(n4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(n7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(n0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(PainelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(n2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(n5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(n8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(virgula, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelTelaPrincipalLayout.createSequentialGroup()
                                        .addComponent(limparTudo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(adicao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(PainelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PainelTelaPrincipalLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(PainelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(n9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(n6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(PainelTelaPrincipalLayout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(parenteses, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10)))
                        .addGroup(PainelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PainelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(multiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(porcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(apagar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(areaDeCalculo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        PainelTelaPrincipalLayout.setVerticalGroup(
            PainelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTelaPrincipalLayout.createSequentialGroup()
                .addComponent(titulo)
                .addGroup(PainelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelTelaPrincipalLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(PainelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n9)
                            .addComponent(n8)
                            .addComponent(n7)))
                    .addGroup(PainelTelaPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(areaDeCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(PainelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(porcentagem)
                            .addComponent(subtracao)
                            .addComponent(adicao)
                            .addComponent(limparTudo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(divisao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PainelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n6)
                            .addComponent(n5)
                            .addComponent(n4)
                            .addComponent(multiplicacao))))
                .addGap(16, 16, 16)
                .addGroup(PainelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n1)
                    .addComponent(n2)
                    .addComponent(n3)
                    .addComponent(igual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n0)
                    .addComponent(virgula)
                    .addComponent(parenteses)
                    .addComponent(apagar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelTelaPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelTelaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void areaDeCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaDeCalculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaDeCalculoActionPerformed

    private void subtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtracaoActionPerformed
         // TODO add your handling code here:
         areaDeCalculo.setText(areaDeCalculo.getText()+"-");
    }//GEN-LAST:event_subtracaoActionPerformed

    private void n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n2ActionPerformed
        // TODO add your handling code here:
         areaDeCalculo.setText(areaDeCalculo.getText()+"2");
    }//GEN-LAST:event_n2ActionPerformed

    private void n5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n5ActionPerformed
        // TODO add your handling code here:
        areaDeCalculo.setText(areaDeCalculo.getText()+"5");
    }//GEN-LAST:event_n5ActionPerformed

    private void n7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n7ActionPerformed
        // TODO add your handling code here:
        areaDeCalculo.setText(areaDeCalculo.getText()+"7");
    }//GEN-LAST:event_n7ActionPerformed

    private void n8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n8ActionPerformed
        // TODO add your handling code here:
        areaDeCalculo.setText(areaDeCalculo.getText()+"8");
    }//GEN-LAST:event_n8ActionPerformed
          // metodo para calcular 
       private double equacao (String expressao){
        return new Object(){
            // variavel de percorrer os caracteres 
            int posicao = -1;
            int ch;
            
            // avançar os proximos caracteres da expressao 
            void nextChar(){
                // variavel do caracteres 
                // lengh () ele verifica o tamanho de um texto 
                ch = (++posicao < expressao.length()) ? expressao.charAt(posicao) : -1;
            
            }//final do nextChar()
            
            // verificando a divisao dos caracteres 
            boolean eat (int valores){
                //percorrendo o vetor até achar o espaço em branco 
                while(ch == ' ')nextChar();
                //se ch for um numero entao retorne verdadeiro 
                if(ch == valores) {
                    nextChar();// converte o numero em caracter
                    return true; //retorne verdadeiro 
                }else{//se não retorne falso
                    return false; // retornando falso 
                }// final do if else 
                
            }// final do metodo eat 
            
            //metodo para analise principal dos calculos 
            double calculando (){
                // chamando o metodo de reconhecimento dos caracteres 
                nextChar ();
                //criando variável de calculo x 
                double x= somarSubtrair();
                //verificando se existe mais caractere
                if(posicao<expressao.length()) 
                    //tratando os erros do sistema 
                    throw new RuntimeException("Erro: "+ (char)ch);
                return x;
            }// final do calculando 
            
            // Analisar as expressoes (adicao, subtração)
            double somarSubtrair(){
                double x = dividirMultiplicar();
                //for para ir somando 
                for (;;){
                    // eat função de comparacao de caractere
                    //se for + ele vai somando os numeros 
                    if (eat('+')) x+= dividirMultiplicar(); //adicao
                    //se nao, se for - ele vai subtraindo 
                    else if (eat('-')) x-= dividirMultiplicar(); //subtracao
                    // se nao ele so retorna 
                    else return x;
                }
            
            }// final da soma
            
            double dividirMultiplicar(){
                double x = fatores();
                //for para ir dividindo 
                for (;;){
                    // eat função de comparacao de caractere
                    //se for / ele vai dividindo os numeros 
                    if (eat('x')) x*= fatores(); //divisão
                    //se nao, se for x ele vai multiplicando 
                    else if (eat('/')) x/= fatores(); //multiplicação 
                    // se nao ele so retorna 
                    else return x;
                }
            
            }// fim do metodo dividirMultiplicar
            
            // metodo para considerar o calculo dos parenteses 
            
            //calculando a porcentagem 
            double porcentagem (){
                if (eat('+')) return porcentagem();
                if (eat('-')) return  -porcentagem();
                //x é o valor que vai receber a porcentagem 
                double x = fatores();
                //y é o valor a qual vamos adicionar a porcentagem 
                double y = fatores();
                double z=0;
                //se usuário tiver digitado 
                if (eat('%')){
                    z= x*y / 100;
                    x+=z;
                }//fim do if 
                return x;
            }// final do metodo porcentagem 
            
            //metodo para considerar o calculo dos parenteses 
            double fatores(){
                //corrigindo os erros de + e - daws operações 
                if(eat('+')) return fatores ();
                if (eat('-')) return fatores ();
                // pegando o inicio do vetor 
                int inicioPosicao = this.posicao;
                //variavel do calculo 
                double x ;
                // procurando os parenteses()
                if (eat('(')){
                    x = somarSubtrair();
                    eat(')');
                    //verificando os numeros digitados 
                }else if ((ch >= '0' && ch<='9' || ch=='.')){
                    while ((ch >= '0' && ch<='9') || ch=='.') nextChar();
                    //converter os caracteres em numeros 
                    x = Double.parseDouble(expressao.substring(inicioPosicao, this.posicao));
                }else{
                    // tratando erros nas variaveis 
                    throw new RuntimeException("Erros: "+ (char)ch);
                
                }// final do else 
                  return x;   
            }// final do metodo fatores 
        
        }.calculando(); // final do return new object 
        
         } // final do metodo equacao
                           
    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
        //capturar o texto da aula de calculo 
        //getText() - captura o que tem escrito 
        //setText() - escreve algo dentro 
        try{
        String expressaoCalculo = areaDeCalculo.getText();
        //chamando o metodo de fazer o calculo e passando o calculo
        double resultado = equacao (expressaoCalculo);
        areaDeCalculo.setText(String.valueOf(resultado));
        }catch(Exception e){
            areaDeCalculo.setText("Erro no calculo"+e);
        }
    }//GEN-LAST:event_igualActionPerformed

    private void limparTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparTudoActionPerformed
        // TODO add your handling code here:
        areaDeCalculo.setText("");
    }//GEN-LAST:event_limparTudoActionPerformed

    private void n0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n0ActionPerformed
        // TODO add your handling code here:
        areaDeCalculo.setText(areaDeCalculo.getText()+"0");
    }//GEN-LAST:event_n0ActionPerformed
         //botao que apaga a ultima coisa digitada 
    private void apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarActionPerformed
        // TODO add your handling code here:
        //capturando o texto digitado 
        String textoAtual = areaDeCalculo.getText();
        //verificar se o texto esta vazio ou não 
        //se texto for maior que 0 
        if (textoAtual.length()>0){
            //então exclua o ultimo caracter digitado
            //substring subdivide a palavra letra por letra
            //substring(posicaoinicial,tamanho,posicaofinal)
            textoAtual = textoAtual.substring(0,textoAtual.length()-1);//apagando letra por letra 
            areaDeCalculo.setText(textoAtual);
        }//fim do if
    }//GEN-LAST:event_apagarActionPerformed

    private void n9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n9ActionPerformed
        // TODO add your handling code here:
        areaDeCalculo.setText(areaDeCalculo.getText()+"9");
    }//GEN-LAST:event_n9ActionPerformed

    private void n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1ActionPerformed
        // TODO add your handling code here:
        areaDeCalculo.setText(areaDeCalculo.getText()+"1");
    }//GEN-LAST:event_n1ActionPerformed

    private void n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n3ActionPerformed
        // TODO add your handling code here:
        areaDeCalculo.setText(areaDeCalculo.getText()+"3");
    }//GEN-LAST:event_n3ActionPerformed

    private void n4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n4ActionPerformed
        // TODO add your handling code here:
        areaDeCalculo.setText(areaDeCalculo.getText()+"4");
    }//GEN-LAST:event_n4ActionPerformed

    private void n6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n6ActionPerformed
        // TODO add your handling code here:
        areaDeCalculo.setText(areaDeCalculo.getText()+"6");
    }//GEN-LAST:event_n6ActionPerformed

    private void virgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_virgulaActionPerformed
        // TODO add your handling code here:
        areaDeCalculo.setText(areaDeCalculo.getText()+",");
    }//GEN-LAST:event_virgulaActionPerformed
     //variavel para verificar se o ( foi aberto
    //inicialmente o parentese não foi aberto 
    boolean parenteseAberto =false;
    private void parentesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentesesActionPerformed
        // TODO add your handling code here:
        //se parentese ainda não foi aberto 
        if (parenteseAberto==false){
            //abra o parentese
            areaDeCalculo.setText(areaDeCalculo.getText() +"(");
            //parentese agora foi aberto 
            parenteseAberto=true; 
            
        }else{//parentese já está aberto
            //fechando parentese 
            areaDeCalculo.setText(areaDeCalculo.getText() +")");
            parenteseAberto=false; //parentese não está mais aberto
        }
    }//GEN-LAST:event_parentesesActionPerformed

    private void adicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicaoActionPerformed
        // TODO add your handling code here:
        areaDeCalculo.setText(areaDeCalculo.getText()+"+");
    }//GEN-LAST:event_adicaoActionPerformed

    private void porcentagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porcentagemActionPerformed
        // TODO add your handling code here:
        areaDeCalculo.setText(areaDeCalculo.getText()+"%");
    }//GEN-LAST:event_porcentagemActionPerformed

    private void divisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisaoActionPerformed
        // TODO add your handling code here:
        areaDeCalculo.setText(areaDeCalculo.getText()+"/");
    }//GEN-LAST:event_divisaoActionPerformed

    private void multiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicacaoActionPerformed
        // TODO add your handling code here:
        areaDeCalculo.setText(areaDeCalculo.getText()+"x");
    }//GEN-LAST:event_multiplicacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelTelaPrincipal;
    private javax.swing.JButton adicao;
    private javax.swing.JButton apagar;
    private javax.swing.JTextField areaDeCalculo;
    private javax.swing.JButton divisao;
    private javax.swing.JButton igual;
    private javax.swing.JButton limparTudo;
    private javax.swing.JButton multiplicacao;
    private javax.swing.JButton n0;
    private javax.swing.JButton n1;
    private javax.swing.JButton n2;
    private javax.swing.JButton n3;
    private javax.swing.JButton n4;
    private javax.swing.JButton n5;
    private javax.swing.JButton n6;
    private javax.swing.JButton n7;
    private javax.swing.JButton n8;
    private javax.swing.JButton n9;
    private javax.swing.JButton parenteses;
    private javax.swing.JButton porcentagem;
    private javax.swing.JButton subtracao;
    private javax.swing.JLabel titulo;
    private javax.swing.JButton virgula;
    // End of variables declaration//GEN-END:variables
}
